# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 07:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_detail', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubCategory',
            new_name='SubCategoryModel',
        ),
    ]
