# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_detail', '0002_auto_20170605_0745'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('price', models.IntegerField()),
                ('is_child', models.BooleanField(default=False)),
                ('is_parent', models.BooleanField(default=False)),
                ('is_adult', models.BooleanField(default=False)),
                ('image', models.ImageField(default=b'package/no-image.png', upload_to=b'package')),
                ('serves_type', models.CharField(blank=True, choices=[(b'sub', b'Subscription'), (b'sess', b'Session')], max_length=4)),
                ('is_trial', models.BooleanField(default=False)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_detail.CompanyModel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
