# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 07:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company_detail', '0002_wishlistmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='likes',
            field=models.ManyToManyField(related_name='review_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
