# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 11:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company_detail', '0004_auto_20170605_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('given_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('given_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_detail.CompanyModel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
