# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_detail', '0005_reviewmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='image',
            field=models.ImageField(default=b'package/no-image.png', upload_to=b'review'),
        ),
    ]
