# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_detail', '0006_reviewmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='answers',
            field=models.ManyToManyField(blank=True, to='company_detail.AnswerModel'),
        ),
    ]
